#!/bin/bash
# CollectionBuilder Deployment Script
# Generated by Manage Digital Ingest
#
# IMPORTANT: Run this script FROM your CollectionBuilder project directory!
# cd to your project before running this script!
#
# This script copies the updated CSV file and updates _config.yml

set -e  # Exit on error

echo "=========================================="
echo "CollectionBuilder Deployment Script"
echo "=========================================="
echo ""

# Check if we're in a CollectionBuilder project directory
if [ ! -f "_config.yml" ]; then
    echo "ERROR: _config.yml not found in current directory"
    echo "Please run this script from your CollectionBuilder project root directory"
    exit 1
fi

# Check if _data directory exists
if [ ! -d "_data" ]; then
    echo "Creating _data directory..."
    mkdir -p _data
fi

# Copy the updated CSV file
echo "Copying CSV file to _data directory..."
cp "/Users/mcfatem/GitHub/manage-digital-ingest-flet-CollectionBuilder/storage/temp/file_selector_20251205_232713_924e1890/gdp-oh-metadata-fields-11-23-25_20251205_232713.csv" "_data/gdp-oh-metadata-fields-11-23-25_20251205_232713.csv"

if [ $? -eq 0 ]; then
    echo "✓ CSV file copied successfully: _data/gdp-oh-metadata-fields-11-23-25_20251205_232713.csv"
else
    echo "✗ Failed to copy CSV file"
    exit 1
fi
# Create _data/transcripts directory if it doesn't exist
if [ ! -d "_data/transcripts" ]; then
    echo "Creating _data/transcripts directory..."
    mkdir -p _data/transcripts
fi

# Copy transcript CSV files (following symbolic links to get actual files)
echo ""
echo "Copying transcript CSV files to _data/transcripts/..."
TRANSCRIPT_COUNT=0
for csv_file in "/Users/mcfatem/GitHub/manage-digital-ingest-flet-CollectionBuilder/storage/temp/file_selector_20251205_232713_924e1890/TRANSCRIPTS"/*.csv; do
    if [ -f "$csv_file" ] || [ -L "$csv_file" ]; then
        # Use -L flag to follow symbolic links and copy the actual file
        cp -L "$csv_file" "_data/transcripts/"
        if [ $? -eq 0 ]; then
            TRANSCRIPT_COUNT=$((TRANSCRIPT_COUNT + 1))
            echo "✓ Copied: $(basename "$csv_file")"
        else
            echo "✗ Failed to copy: $(basename "$csv_file")"
        fi
    fi
done
echo "✓ Copied $TRANSCRIPT_COUNT transcript CSV file(s) to _data/transcripts/"


# Update _config.yml
echo ""
echo "Updating _config.yml metadata reference..."

# Check if metadata key exists in _config.yml
if grep -q "^metadata:" "_config.yml"; then
    # Backup _config.yml
    cp _config.yml _config.yml.backup
    echo "  (Backup created: _config.yml.backup)"
    
    # Update the metadata line
    sed -i.tmp 's/^metadata:.*/metadata: gdp-oh-metadata-fields-11-23-25_20251205_232713/' _config.yml
    rm -f _config.yml.tmp
    
    echo "✓ Updated metadata key in _config.yml"
    echo "  New value: metadata: gdp-oh-metadata-fields-11-23-25_20251205_232713"
else
    echo "⚠ Warning: 'metadata:' key not found in _config.yml"
    echo "  Please manually add the following line to _config.yml:"
    echo "  metadata: gdp-oh-metadata-fields-11-23-25_20251205_232713"
fi

echo ""
echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review the changes: git diff _config.yml"
echo "2. Test locally: bundle exec jekyll s"
echo "3. Commit and push when ready"
echo ""
